# Generated by Django 6.0.5 on 2026-05-11 06:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SentimentAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('sentiment_label', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral')], max_length=20)),
                ('sentiment_score', models.FloatField()),
                ('sentiment_all_scores', models.JSONField(default=dict)),
                ('dominant_emotion', models.CharField(choices=[('joy', 'Joy'), ('anger', 'Anger'), ('fear', 'Fear'), ('sadness', 'Sadness'), ('surprise', 'Surprise'), ('disgust', 'Disgust'), ('neutral', 'Neutral')], max_length=20)),
                ('emotion_score', models.FloatField()),
                ('all_emotions', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sentiment_analyses',
                'ordering': ['-created_at'],
            },
        ),
    ]
